export enum LangEnum{

    af=       "af",
    al=         "al",
    ar=         "ar",
    az=         "az",
    bg=         "bg",
    ca=         "ca",
    cz=         "cz",
    da=         "da",
    de=         "de",
    el=         "el",
    en=         "en",
    eu=         "eu",
    fa=         "fa",
    fi=         "fi",
    fr=         "fr",
    gl=         "gl",
    he=         "he",
    hi=         "hi",
    hr=         "hr",
    hu=         "hu",
    id=         "id",
    it=         "it",
    ja=         "ja",
    kr=         "kr",
    la=         "la",
    lt=         "lt",
    mk=         "mk",
    no=         "no",
    nl=         "nl",
    pl=         "pl",
    pt=         "pt",
    pt_br=      "pt_br",
    ro=         "ro",
    ru=         "ru",
    se=	        "se",
    sk=         "sk",
    sl=         "sl",
    es=	        "es",
    sr =        "sr",
    th =        "th",
    tr =        "tr",
    uk=         "uk",
    vi =        "vi",
    zh_cn=      "zh_cn",
    zh_tw=      "zh_tw",
    zu=         "zu",


}